// <auto-generated />
using System;
using AldoGiovanniGiacomo.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AldoGiovanniGiacomo.API.Migrations
{
    [DbContext(typeof(AldoGiovanniGiacomoAPIContext))]
    partial class AldoGiovanniGiacomoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AldoGiovanniGiacomo.API.DTOs.ActorDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nickname")
                        .HasMaxLength(50);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = new DateTime(1958, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Palermo",
                            Name = "Aldo",
                            Surname = "Baglio"
                        },
                        new
                        {
                            Id = 2,
                            Birth = new DateTime(1957, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Milano",
                            Name = "Giovanni",
                            Surname = "Storti"
                        },
                        new
                        {
                            Id = 3,
                            Birth = new DateTime(1956, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Villa Cortese",
                            Name = "Giacomo",
                            Nickname = "Giacomino",
                            Surname = "Poretti"
                        });
                });

            modelBuilder.Entity("AldoGiovanniGiacomo.API.DTOs.MovieDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Aldo Baglio, Giovanni Storti, Giacomo Poretti, Massimo Venier",
                            Title = "Tre uomini e una gamba",
                            Year = 1997
                        },
                        new
                        {
                            Id = 2,
                            Director = "Aldo Baglio, Giovanni Storti, Giacomo Poretti, Massimo Venier",
                            Title = "Così è la vita",
                            Year = 1998
                        },
                        new
                        {
                            Id = 3,
                            Director = "Paolo Costella",
                            Title = "Tutti gli uomini del deficiente",
                            Year = 1999
                        },
                        new
                        {
                            Id = 4,
                            Director = "Aldo Baglio, Giovanni Storti, Giacomo Poretti, Massimo Venier",
                            Title = "Chiedimi se sono felice",
                            Year = 2000
                        },
                        new
                        {
                            Id = 5,
                            Director = "Aldo Baglio, Giovanni Storti, Giacomo Poretti, Massimo Venier",
                            Title = "La leggenda di Al, John e Jack",
                            Year = 2002
                        },
                        new
                        {
                            Id = 6,
                            Director = "Massimo Venier",
                            Title = "Tu la conosci Claudia?",
                            Year = 2004
                        },
                        new
                        {
                            Id = 7,
                            Director = "Arturo Brachetti, Rinaldo Gaspari",
                            Title = "Anplagghed al cinema",
                            Year = 2006
                        },
                        new
                        {
                            Id = 8,
                            Director = "Marcello Cesena",
                            Title = "Il cosmo sul comò",
                            Year = 2008
                        },
                        new
                        {
                            Id = 9,
                            Director = "Paolo Genovese",
                            Title = "La banda dei Babbi Natale",
                            Year = 2010
                        },
                        new
                        {
                            Id = 10,
                            Director = "Arturo Brachetti",
                            Title = "Ammutta mudica al cinema",
                            Year = 2013
                        },
                        new
                        {
                            Id = 11,
                            Director = "Aldo Baglio, Giovanni Storti, Giacomo Poretti, Morgan Bertacca",
                            Title = "Il ricco, il povero e il maggiordomo",
                            Year = 2014
                        },
                        new
                        {
                            Id = 12,
                            Director = "Aldo Baglio, Giovanni Storti, Giacomo Poretti, Morgan Bertacca",
                            Title = "Fuga da Reuma Park",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("AldoGiovanniGiacomo.API.DTOs.QuoteDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<int>("MovieId");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 1,
                            Content = "[Leggendo le istruzioni di montaggio del fucile, allontana Jack] Tenere lontano dalla portata dei bambini...",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 2,
                            Content = "[Dopo che Chiara propone di fare un bagno in un lago] No eh, ragazzi, simpatia, va bene, si scherza, si gioca, gli ho fatto anche guidare la macchina, però siamo già in ritardo! Non scherziamo... [si gira e non vede più nessuno in macchina] Va bene. Ma solo cinque minuti!",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 2,
                            Content = "Ma hai visto quel cane lì? Gli hanno montato... le tibie al contrario? [riferito al bulldog Ringhio]",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 2,
                            Content = "[Dando istruzioni ad Aldo su come sistemare il pacco nel bagagliaio] Dai, mettila bene... Mettila più dritta! Mettilo fino in fondo... Sdraiato però, mettilo piatto! Piatto! Metti che succede qualcosa, mettilo piatto!",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 2,
                            Content = "Un latte macchiato tiepido, senza schiuma e con poco caffè... tiepido, eh, non freddo! Poi gli chiedi le cose... [al bar, poco dopo gli viene servito il latte] Freddo, lo sapevo io!",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 7,
                            ActorId = 2,
                            Content = "Mattone polacco minimalista di scrittore morto suicida giovanissimo! Copie vendute: due. [parlando del libro che sta comprando Giacomo]",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 8,
                            ActorId = 2,
                            Content = "Ma vai! Ma vieni! Ma chi sono? Eh, pirletti, dimmi, chi sono? Altro che la tua ruota! [vede il padre dei bambini che lo guarda storto] Chi arriva ultimo [all'auto] è pirla!",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 9,
                            ActorId = 2,
                            Content = "Anche il capitano del Titanic lo diceva: 'Ma no, ma no, è solo un rumorino! Da niente!' [riferito ad un rumore proveniente dalla macchina]",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 10,
                            ActorId = 2,
                            Content = "Sì, ma a te bisogna portarti in giro legato... [riferito a Aldo che fa cadere per la seconda volta i barattoli davanti all'officina del meccanico]",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 11,
                            ActorId = 1,
                            Content = "A volte dorme di più lo sveglio che il dormiente!",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 12,
                            ActorId = 1,
                            Content = "Una rondine non vola solo e sempre a primavera.",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 13,
                            ActorId = 2,
                            Content = "Ma vieni! Jair! È il ritorno della Grande Inter! È il ritorno! [dopo aver segnato un bel gol in 'Italia-Marocco']",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 14,
                            ActorId = 2,
                            Content = "Questo qui [Giacomo] si deve sposare e siamo in ritardo di una vita... il dietro della macchina... completamente sfasciato... ci ha affidato un bulldog e gli [al suocero] riportiamo... un toporagno... e una gamba da trecento milioni è in mano a una banda di muratori marocchini! Ditemi voi... ",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 15,
                            ActorId = 1,
                            Content = "[Al telefono, chiama il suocero] Pronto, pronto sì, ssss sì ssì sssss stiamo, siam... sìsìsì no, è... la la lascia lasciami... è m mma maria nnn... noo... ss, bè, ss se fosse stato per me... sì... ma io ss sono il primo che che... non ho ca, non ho ca, non ho c... non ho c... [urlando stressato] Allora, mi lasci parlare o no?! Hai capito?! E non ne posso più di ascoltarti, stai parlando solo tu! E mi hai proprio rotto i coglioni, mi hai rotto i coglioni, hai capito?! Perché non sono un automa, sono una persona, e a un certo punto te lo devo proprio dire: vaffanculo! Vaffanculo!! V, A, F, F, 'ncuuuulo!!! Tu, il tuo negozio, la tua villa di merda, mi fai schifo, strooonzoo!! [chiude furiosamente la chiamata e gli altri lo guardano colpiti] Era occupato.",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 16,
                            ActorId = 1,
                            Content = "Giacomino è in bagno... Giacomino sta dormendo... eh sì... sta dormendo in bagno... eh, si vede che si è addormentato mentre stava cagando! Che ne so io! Stiamo arrivando! Sì! Ma stiamo arriva... ma... [Aldo da un'occhiata crudele al cellulare mentre Giuliana ancora blatera] Ma vaffancuuulo! [Aldo getta furiosamente il cellulare in mare dopo essere stato stressato da Giuliana, e Giovanni e Giacomo lo guardano colpiti]",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 17,
                            ActorId = 2,
                            Content = "[Dopo avergli sparato un proiettile in una gamba] Ma non fare polemiche, Jack, ha rimbalzato!",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 18,
                            ActorId = 1,
                            Content = "[Riferito all'enorme compagno di cella che dorme sopra di lui] Crapanzano, meno male che oggi esci... avrò dormito un'ora in due anni!",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 19,
                            ActorId = 2,
                            Content = "[Restituendo alla madre il bambino che gli ha vomitato sulla giacca, affidatogli da una passante] Signora, le do un consiglio: lo faccia vedere da un esorcista.",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 20,
                            ActorId = 2,
                            Content = "[Rivolto a Giacomo che ha lasciato la pistola nel portaoggetti] Ma chi è che ti ha addestrato a te, Topo Gigio?",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 21,
                            ActorId = 2,
                            Content = "[Rivolto a Giacomo che ha lasciato la pistola nel portaoggetti] Ma chi è che ti ha addestrato a te, Topo Gigio?",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 22,
                            ActorId = 1,
                            Content = "Sì, ho conosciuto una ragazza si chiama Clara, è bellissima, è bionda, è bellissima, è... vabbè, più bionda che bellissima...",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 23,
                            ActorId = 1,
                            Content = "[Rivolgendosi a Giacomo che, in una discesa, si era dimenticato di tirare il freno a mano] Mii ma dove hai preso la patente? Alla sala giochi?",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 24,
                            ActorId = 1,
                            Content = "[Mentre lui, Giovanni e Giacomo vengono inseguiti da un elicottero e dalle volanti della polizia] Ma che cosa vogliono fare?! Che cosa credono di fare?!? Cos'è, Apocalypse Now?!?",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 25,
                            ActorId = 1,
                            Content = "Che cos'è il rancore? Il rancore è quella cosa... Che quando... Lo so, ti si... Eh la... Cioè il rancore, lo dice la parola stessa: ran-core, che la... Bisogna... Maria, ma proprio io dovevo fare la voce fuori campo!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 26,
                            ActorId = 1,
                            Content = "Maria, che dolore! Ma porca miseria! Miliardi di piastrine perse per sempre!! [vedendo il sangue uscirgli dal naso dopo aver preso una testata da Dalia]",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 27,
                            ActorId = 1,
                            Content = "Le mutande! Quando le cerchi non si trovano mai!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 28,
                            ActorId = 1,
                            Content = "Se non mi licenziano loro, mi licenzio da solo, perché li capisco.",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 29,
                            ActorId = 1,
                            Content = "Lo so, visti così sembravamo tre coglioni... e forse lo eravamo. [raccontando della situazione lavorativa di lui, Giovanni e Giacomo]",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 30,
                            ActorId = 1,
                            Content = "Insomma credevamo che fosse uno di quei giorni in cui tutto sta per iniziare, invece era solo l'inizio della fine!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 31,
                            ActorId = 2,
                            Content = "Chiedimi se sono felice!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 32,
                            ActorId = 2,
                            Content = "Ma cosa c'hai nel cervello? Le scimmie urlatrici?",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 33,
                            ActorId = 2,
                            Content = "Anche mia nonna quando doveva mettermi le supposte da bambino me le spalmava sul sellino della bicicletta!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 34,
                            ActorId = 1,
                            Content = "Perché l'amore, quando ci si mette, è veramente bastardo.",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 35,
                            ActorId = 1,
                            Content = "Giacomino, ti prego, scarricamela!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 36,
                            ActorId = 2,
                            Content = "Giacomo, guarda, parlare con te o parlare con Biscardi è la stessa cosa...",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 37,
                            ActorId = 1,
                            Content = "Ma possibile che come ti muovi pesti una merda? In un colpo solo gli hai fatto fuori il lavoro e la fidanzata! Adesso prendi una macchina, gli metti sotto la madre e finisci il lavoro. E comunque Giacomino se ti chiedo un favore, domani, non farmelo!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 38,
                            ActorId = 2,
                            Content = "Aldo, non è che perché hai un frigo degli anni '60 ci devi tener dentro la roba degli anni '60!",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 39,
                            ActorId = 2,
                            Content = "Ma che cosa cazzo me ne frega di cosa avete bevuto?? Piuttosto dimmi cosa ti ha detto! [Aldo accende lo stereo] Ma la vuoi spegnere quella merda di musica o no??",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 40,
                            ActorId = 1,
                            Content = "Per favore, lascia stare... Giacomino, vattene, lasciami solo. [dopo la furibonda rabbia di Giovanni che ha distrutto tutta la scenografia]",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 41,
                            ActorId = 1,
                            Content = "Avete presente la teoria del piano inclinato? No? Ve la spiego. Se mettete una pallina su un piano inclinato la pallina comincia a scendere, e per quanto impercettibile sia l'inclinazione, inizia a correre e correre sempre più veloce. Fermarla, è impossibile. Ma per fortuna gli uomini non sono palline: basta un gesto, un'occhiata, una frase qualsiasi a fermare il corso delle cose.",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 42,
                            ActorId = 1,
                            Content = "E voi chi minchia siete?",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 43,
                            ActorId = 2,
                            Content = "Tanti auguri a Jack | Tanti auguri a Jack | Tanti auguri impasticcomane! | Tanti auguri a te!",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 44,
                            ActorId = 3,
                            Content = "Anzi fai una cosa, Johnny: ammazzalo così la smette di soffrire, va! [riferito ad Al che ha perso la memoria]",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 45,
                            ActorId = 3,
                            Content = "Johnny, Johnny, non piangere, che diventi brutto!",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 46,
                            ActorId = 2,
                            Content = "Le ha spente con la tosse... [le candeline] [riferito a Jack e alla sua salute 'non proprio di ferro']",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 47,
                            ActorId = 3,
                            Content = "Ma quant'è bella la mafia!",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 48,
                            ActorId = 2,
                            Content = "Buongiorno signora e benvenuta. È un piacere accoglierLa in questa città di New York, città bellissima ma non altrettanto che Lei. [John, che si studia il benvenuto da fare alla zia del boss Genovese che è in arrivo a New York]",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 49,
                            ActorId = 2,
                            Content = "Jack, noi stiamo mettendo la nostra vita nelle sue mani e questo non sa neanche come si chiama!  [riferito ad Al, che aveva appena detto di chiamarsi Niccolò Carosio]",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 50,
                            ActorId = 3,
                            Content = "Johnny, a te te lo devono dare il premio Nobel per la mafia, e se non te lo danno è perché è tutto un magna magna.",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 51,
                            ActorId = 2,
                            Content = "Che tocchi? Che tocchi, Jack? Non è roba per te! Non hai mai avuto manualità!",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 52,
                            ActorId = 1,
                            Content = "E vedi di non farmi diventare Al tre dita. [riferito a Jack che attacca un quadro con la pistola]",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 53,
                            ActorId = 1,
                            Content = "Senta, io mi prendo le mie responsabilità, ma siamo sicuri che il chiosco non sia abusivo? [dopo aver investito una bancarella]",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 54,
                            ActorId = 1,
                            Content = "Ma proprio adesso che mi stavo innamorando, che ero deciso di fare il passo più lungo della gamba! Io lo so quando è crollato tutto: è stato quel maledetto momento in cui abbiamo visto insieme il marito! [piangendo]",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 55,
                            ActorId = 1,
                            Content = "Claudia non esiste, suo marito non esiste! Claudia non esiste, suo marito non esiste!",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 56,
                            ActorId = 2,
                            Content = "Senti, 'NonSoloTaxi', ma come guidi? Porca puttana, va' come hai conciato la macchina... Allora, di constatazione amichevole non ne parliamo neanche, eh, tanto nessun giudice ti darebbe ragione! [dopo aver tamponato Aldo]",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 57,
                            ActorId = 1,
                            Content = "C'è un posto dove posso vomitare un attimo? Un posto specifico per il vomito, insomma: un vomituario, anche di modeste proporzioni.",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 58,
                            ActorId = 1,
                            Content = "Se queste mura potessero parlare, si dovrebbero confessare! Fuochi! Fiamme! Sodoma! Gamarra! Eh?",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 59,
                            ActorId = 1,
                            Content = "Miiii, che bello! Unplugged!",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 60,
                            ActorId = 2,
                            Content = "Allora lo vogliamo far smettere di piangere 'sto bambino o no, eh? Sono le tre di notte! [più furioso di prima] Li vogliamo spendere 'sti due soldi per farlo visitare da uno specialista o no, eh? Ve ne consiglio uno: Dott. Sirchioli. 6832173! [sempre più infuriato] Cosa faccio, chiamo i carabinieri, eh??? [sentendo il bambino dei vicini che piange forte]",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 61,
                            ActorId = 2,
                            Content = "[Ad Aldo, che indossa una camicia a fiori] Ma come sei vestito? Stai andando al Carnevale di Venezia? Sembri Brighella con le scarpe di Pantalone!",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 62,
                            ActorId = 1,
                            Content = "Equilibre, equilibre, equlibre...",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 63,
                            ActorId = 2,
                            Content = "Scivolement, scivolement, scivolement...",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 64,
                            ActorId = 1,
                            Content = "Noi siamo una squadra. Ma che dico una squadra... Noi siamo la squadra per antonomasia! I Charlatans!",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 65,
                            ActorId = 1,
                            Content = "Un'altra emergenza... Il pitone dei Galbiati si è mangiato il gatto... gli avevo detto di non farli giocare assieme...",
                            MovieId = 9
                        });
                });

            modelBuilder.Entity("AldoGiovanniGiacomo.API.DTOs.QuoteDTO", b =>
                {
                    b.HasOne("AldoGiovanniGiacomo.API.DTOs.ActorDTO", "Actor")
                        .WithMany("Quotes")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AldoGiovanniGiacomo.API.DTOs.MovieDTO", "Movie")
                        .WithMany("Quotes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
